name: gen_lang
description: >-
  gen_lang is a dart library for internationalization. Extracts messages
  to generate dart files required by Intl
version: 0.1.4
homepage: https://github.com/KingWu/gen_lang

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  ansicolor: ^2.0.2
